# Background
In the world today, there is a growing problem of increasingly poor health across the globe. While life expectancy has increased, the amount of years spent in poor health has also increased proportionally.[³](#ref3) Within the United States in particular, recent reseach has revealed not only that "the U.S. [has] the lowest life expectancy among high-income countries, but it also has the highest rates of avoidable deaths" despite spending almost 18% of its Gross Domestic Product (GDP) on healthcare. In comparison, the second-highest spender on healthcare is Germany at 12.8%. Furthermore, the United States has almost double the obesity rate than other high-income countries and its citizens are more likely to suffer with multiple chronic conditions.[¹⁰](#ref10) It is no question that finding a solution to this health endemic is vital to Americans' health- but what is the answer?

Other research has already attempted to answer this question and found that:

> [a]lthough spending did not correlate meaningfully with health, certain features of the [United States’] health care system did correlate highly with health outcomes, notably rates of health insurance coverage and access to affordable care (not having to forego care due to cost)... [H]ealth outcomes were better in states with adequate primary care services to manage chronic diseases and prevent hospitalizations for conditions like heart attacks, congestive heart failure, and pneumonia.[¹⁴](#ref14)

This comes as no surprise; preventative care is generally accepted as one of the most important factors in maintaining health. Daily exercise, access to healthy foods, minimal consumption of alcohol, and not smoking are all important factors for improving and maintaining one’s health.[¹¹](#ref11) The above underscores the reality that, even if a person is uninsured, having access to primary care helps prevent against their need to go to a hospital and risk getting caught with a tremendous bill due to their uninsured status. 

::: {.callout-tip collapse="true"}
# But how can an uninsured individual even access primary care to avoid hospital fees?
Free clinics and [Direct Primary Care (DPC)](https://www.aafp.org/family-physician/practice-and-career/delivery-payment-models/direct-primary-care.html) models offer the solution. While free clinics are, of course, free, they require patients to make less than a certain amount to qualify for care. On the other hand, DPCs do not bill insurance and charge a flat-rate monthly membership instead, thus allowing individuals access to primary care at an accessible and affordable cost.[¹](#ref1) In particular, [DPCs paired with a healthshare](https://www.dpcfrontier.com/health-sharing-ministries) offer people the most options at an affordable rate, as their healthshare could cover the cost of specialists, imaging, DPC membership fees, and other healthcare-related expenses as needed.[⁶](#ref6)
:::

As for insurance's impact on health, measuring it becomes tricky in the United States. Though countries with univeral public health insurance are healthier at the global level, the United States is the only high-income country to not offer health coverage to all citizens.[⁹](#ref9)𝄒[¹⁰](#ref10) Instead, both private and public healthcare co-exist, where neither option is available to all. 

In the United States, public healthcare is available to those who are disabled or over 65 years old through Medicare. Medicare is not always free, but generally more affordable than private health insurance. Low income Americans can also receive free public healthcare through Medicaid. Public healthcare is funded through both federal and state health expenditures.

While this system may have been implemented with good intentions, the current reality is that for-profit institutions are disincentivized from accepting Medcaid and Medicare patients. This is because public health insurance in the United States reimburses health centers at a low rate- much lower than private insurance. As of 2022, when our data was collected, Medicare reimbursement was at an all-time low. By the end of the year, this added up to $99.2 billion in unpaid Medicare treatments.[²](#ref2)

Sadly, research has also shown that Medicaid patients have reduced access to care.[¹²](#ref12) Medicaid populations are made up of a more diverse population than the rest of the United States' population, which means our minority populations and those most of need in care have the hardest time getting it.[⁴](#ref4) This is a problem and needs a solution. Our research seeks to face this problem by providing knowledge and resources to those who have found themselves in need of care and/or basic needs but cannot access or afford it.