# References

1. <a id="ref1"></a> AAFP. (n.d.). *Direct Primary Care.* AAFP. [https://www.aafp.org/family-physician/practice-and-career/delivery-payment-models/direct-primary-care.html](https://www.aafp.org/family-physician/practice-and-career/delivery-payment-models/direct-primary-care.html)
2. <a id="ref2"></a> American Hospital Association. (n.d.). *Infographic: Medicare Significantly Underpays Hospitals for Cost of Patient Care.* American Hospital Association. [https://www.aha.org/2024-01-10-infographic-medicare-significantly-underpays-hospitals-cost-patient-care](https://www.aha.org/2024-01-10-infographic-medicare-significantly-underpays-hospitals-cost-patient-care)
3. <a id="ref3"></a> Broom, D. (2022, April 5). *We’re spending more years in poor health than at any point in history. How can we change this?* World Economic Forum. [https://www.weforum.org/agenda/2022/04/longer-healthier-lives-everyone/#:~:text=Global%20Health,-Follow&text=Life%20expectancy%20is%20rising%2C%20but,six%20years%20of%20quality%20life.](https://www.weforum.org/agenda/2022/04/longer-healthier-lives-everyone/#:~:text=Global%20Health,-Follow&text=Life%20expectancy%20is%20rising%2C%20but,six%20years%20of%20quality%20life.)
4. <a id="ref4"></a> CMS. (2020). *Race and ethnicity of the national Medicaid and CHIP population in 2020.* CMS. [https://www.medicaid.gov/medicaid/data-and-systems/downloads/macbis/2020-race-etncity-data-brf.pdf](https://www.medicaid.gov/medicaid/data-and-systems/downloads/macbis/2020-race-etncity-data-brf.pdf)
5. <a id="ref5"></a> County Health Rankings & Roadmaps. (2024). *Data & Documentation.* County Health Rankings & Roadmaps. [https://www.countyhealthrankings.org/health-data/methodology-and-sources/data-documentation](https://www.countyhealthrankings.org/health-data/methodology-and-sources/data-documentation)
6. <a id="ref6"></a> DPC Frontier. (n.d.). *Health Care Sharing Ministries.* DPC Frontier. [https://www.dpcfrontier.com/health-sharing-ministries](https://www.dpcfrontier.com/health-sharing-ministries)
7. <a id="ref7"></a> DPC Nation. (n.d.). *Join the Direct Primary Care revolution.* DPC Nation. [https://dpcnation.org/](https://dpcnation.org/)
8. <a id="ref8"></a> EPA. (2023, August 10). *Health status.* EPA. [https://www.epa.gov/report-environment/health-status#:~:text=The%20health%20status%20of%20a,accessibility%20of%20health%20personnel%20and](https://www.epa.gov/report-environment/health-status#:~:text=The%20health%20status%20of%20a,accessibility%20of%20health%20personnel%20and)
9. <a id="ref9"></a> Galvani-Townsend, S., Martinez, I., & Pandey, A. (2022, Nov. 12). Is life expectancy higher in countries and territories with publicly funded health care? Global analysis of health care access and the social determinants of health. *Journal of Global Health, 12*(04091), 1-12. [doi: 10.7189/jogh.12.04091](https://pubmed.ncbi.nlm.nih.gov/36370409/)
10. <a id="ref10"></a> Gunja, M.Z., Gumaz, E.D., & Williams, R.D.II. (2023, Jan. 31). *U.S. Health Care from a Global Perspective, 2022: Accelerating Spending, Worsening Outcomes.* The Commonwealth Fund. [https://www.commonwealthfund.org/publications/issue-briefs/2023/jan/us-health-care-global-perspective-2022](https://www.commonwealthfund.org/publications/issue-briefs/2023/jan/us-health-care-global-perspective-2022) 
11. <a id="ref11"></a> Harvard School of Public Health. (2022, December). *Healthy longevity.* The Nutrition Source. [https://nutritionsource.hsph.harvard.edu/healthy-longevity/](https://nutritionsource.hsph.harvard.edu/healthy-longevity/) 
12. <a id="ref12"></a> Hsiang, W.R., Lukasiewicz, A., Gentry, M., Kim, C., Leslie, M.P., Pelker, R., Forman, H.P. Wiznia, D.H. (2019, Apr. 5). Medicaid patients have greater difficulty scheduling health care appointments compared with private insurance patients: A meta-analysis. *Inquiry: The Journal of Health Care Organization, Provision, and Financing, 56,*(1-9). [https://doi.org/10.1177/004695801983811](https://journals.sagepub.com/doi/10.1177/0046958019838118)
13. <a id="ref13"></a> KFF. (2024). *State Health Facts: Build A Custom State Report* KFF: The independent source for health policy research, polling, and news. [https://www.kff.org/statedata/custom/](https://www.kff.org/statedata/custom/)
14. <a id="ref14"></a> Woolf , S.H., Aron, L., Chapman, D.A., Dubay, L., Zimmerman, E., Snellings, L.C., Hall, L., Haley, A.D., Holla, N., Ayers, K., Lowenstein, C., & Waidmann, T.A. (2016). *The health of the States: How U.S. States compare in health status and the factors that shape health.* Virginia Commonwealth University Center on Society and Health. [https://www.urban.org/sites/default/files/publication/85211/health-of-the-states_6.pdf](https://www.urban.org/sites/default/files/publication/85211/health-of-the-states_6.pdf)


