project:
  type: website
  output-dir: _output

format: 
  html:
    toc: true
    toc-location: left
    theme:
      light: lightly
      dark: darkly
with:
  target: gh-pages
  path: capstone.qmd
lightbox: true
