project:
  type: website
  output-dir: _output

title: "Preventative Care in the United States"
subtitle: "How do preventative healthcare measures impact standard health metrics?"
authors:
  - Frances Romero
  - Haleigh Schwartz
date: today
title-block-banner: true
number-sections: true

format: 
  html:
    toc: true
    toc-location: left
    theme:
      light: lightly
      dark: darkly
    
with:
  target: gh-pages
  path: capstone.qmd

lightbox: true